version: "2"
services:
  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    hostname: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATION_URL=pushover://shoutrrr:ao7guofrpyzu393xqjmp1b19v5rrjb@uy4wtgramowo8fd558j66hmkj2iuki/?priority=-2
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=debian0
    restart: unless-stopped
